#Setup MurderMystery
murdermystery:
  options:
    murder:
      sword-cooldown: 10 # in seconds
    #1 gold per 4 seconds
    gold-spawner-rate: 4
    max-gold-spawned-once: 4
    gold-spawner-world: world
  arena:
    max: 
      x: -220
      y: 85
      z: 178
      world: world
    min:
      x: -206
      y: 77
      z: 159
      world: world
    cauldrons:
      '0':
        x: -210
        y: 78
        z:  164
        world: world
      '1':
        x: -218
        y: 78
        z:  166
        world: world
  join:
    position:
      x: -204.5
      y: 79
      z: 164.5
      world: world
      yaw: 90
      pitch: 0
  warmup:
    world: world
    positions:
      '0':
        x: -213.5
        y: 78
        z: 173.5
      '1':
        x: -216.5
        y: 78
        z: 163.5
      '2':
        x: -215.5
        y: 78
        z: 168.5