#Setup MurderMystery
murdermystery:
  arena:
    max: 
      x: -220
      y: 85
      z: 178
      world: world
    min:
      x: -206
      y: 77
      z: 159
      world: world
  join:
    position:
      x: -204.5
      y: 79
      z: 164.5
      world: world
      yaw: 90
      pitch: 0
  warmup:
    world: world
    positions:
      '0':
        x: -213.5
        y: 78
        z: 173.5
      '1':
        x: -216.5
        y: 78
        z: 163.5
      '2':
        x: -215.5
        y: 78
        z: 168.5